# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\project.ui'
#
# Created: Mon Apr 23 09:09:01 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1137, 825)
        Form.setStyleSheet(_fromUtf8("background:rgb(230, 232, 255)"))
        self.leftView = QtGui.QGraphicsView(Form)
        self.leftView.setEnabled(True)
        self.leftView.setGeometry(QtCore.QRect(70, 110, 471, 261))
        self.leftView.setMouseTracking(True)
        self.leftView.setObjectName(_fromUtf8("leftView"))
        self.rightView = QtGui.QGraphicsView(Form)
        self.rightView.setEnabled(True)
        self.rightView.setGeometry(QtCore.QRect(600, 110, 471, 261))
        self.rightView.setMouseTracking(True)
        self.rightView.setObjectName(_fromUtf8("rightView"))
        self.loadLeft = QtGui.QPushButton(Form)
        self.loadLeft.setGeometry(QtCore.QRect(70, 70, 93, 28))
        self.loadLeft.setObjectName(_fromUtf8("loadLeft"))
        self.loadRight = QtGui.QPushButton(Form)
        self.loadRight.setGeometry(QtCore.QRect(600, 70, 93, 28))
        self.loadRight.setObjectName(_fromUtf8("loadRight"))
        self.model_2 = QtGui.QPushButton(Form)
        self.model_2.setGeometry(QtCore.QRect(70, 30, 93, 28))
        self.model_2.setObjectName(_fromUtf8("model_2"))
        self.modelPath = QtGui.QLineEdit(Form)
        self.modelPath.setEnabled(False)
        self.modelPath.setGeometry(QtCore.QRect(170, 30, 371, 31))
        self.modelPath.setObjectName(_fromUtf8("modelPath"))
        self.weightsPath = QtGui.QLineEdit(Form)
        self.weightsPath.setEnabled(False)
        self.weightsPath.setGeometry(QtCore.QRect(700, 30, 371, 31))
        self.weightsPath.setObjectName(_fromUtf8("weightsPath"))
        self.weights = QtGui.QPushButton(Form)
        self.weights.setGeometry(QtCore.QRect(600, 30, 93, 28))
        self.weights.setObjectName(_fromUtf8("weights"))
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(70, 420, 291, 101))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.leftCol = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leftCol.setObjectName(_fromUtf8("leftCol"))
        self.gridLayout.addWidget(self.leftCol, 1, 1, 1, 1)
        self.leftPatch = QtGui.QPushButton(self.gridLayoutWidget)
        self.leftPatch.setObjectName(_fromUtf8("leftPatch"))
        self.gridLayout.addWidget(self.leftPatch, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.leftRow = QtGui.QLineEdit(self.gridLayoutWidget)
        self.leftRow.setObjectName(_fromUtf8("leftRow"))
        self.gridLayout.addWidget(self.leftRow, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(Form)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(600, 420, 301, 161))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.predictRightPatch = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.predictRightPatch.setObjectName(_fromUtf8("predictRightPatch"))
        self.gridLayout_2.addWidget(self.predictRightPatch, 0, 2, 1, 1)
        self.rightColP = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.rightColP.setEnabled(False)
        self.rightColP.setObjectName(_fromUtf8("rightColP"))
        self.gridLayout_2.addWidget(self.rightColP, 1, 1, 1, 1)
        self.disparityP = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.disparityP.setEnabled(False)
        self.disparityP.setObjectName(_fromUtf8("disparityP"))
        self.gridLayout_2.addWidget(self.disparityP, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.rightRowP = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.rightRowP.setEnabled(False)
        self.rightRowP.setObjectName(_fromUtf8("rightRowP"))
        self.gridLayout_2.addWidget(self.rightRowP, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 2, 1, 1)
        self.leftPatch_2 = QtGui.QGraphicsView(Form)
        self.leftPatch_2.setGeometry(QtCore.QRect(370, 420, 81, 81))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftPatch_2.sizePolicy().hasHeightForWidth())
        self.leftPatch_2.setSizePolicy(sizePolicy)
        self.leftPatch_2.setAutoFillBackground(True)
        self.leftPatch_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.leftPatch_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.leftPatch_2.setObjectName(_fromUtf8("leftPatch_2"))
        self.rightPatchPredict = QtGui.QGraphicsView(Form)
        self.rightPatchPredict.setEnabled(True)
        self.rightPatchPredict.setGeometry(QtCore.QRect(910, 420, 81, 81))
        self.rightPatchPredict.setAutoFillBackground(True)
        self.rightPatchPredict.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightPatchPredict.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightPatchPredict.setObjectName(_fromUtf8("rightPatchPredict"))
        self.disparityP_2 = QtGui.QLineEdit(Form)
        self.disparityP_2.setEnabled(False)
        self.disparityP_2.setGeometry(QtCore.QRect(910, 540, 101, 21))
        self.disparityP_2.setObjectName(_fromUtf8("disparityP_2"))
        self.rightCost = QtGui.QLineEdit(Form)
        self.rightCost.setEnabled(False)
        self.rightCost.setGeometry(QtCore.QRect(910, 760, 108, 21))
        self.rightCost.setObjectName(_fromUtf8("rightCost"))
        self.gridLayoutWidget_4 = QtGui.QWidget(Form)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(600, 640, 301, 111))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.rightCol = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.rightCol.setObjectName(_fromUtf8("rightCol"))
        self.gridLayout_4.addWidget(self.rightCol, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.pushButton, 0, 2, 1, 1)
        self.rightPatch_3 = QtGui.QLineEdit(self.gridLayoutWidget_4)
        self.rightPatch_3.setObjectName(_fromUtf8("rightPatch_3"))
        self.gridLayout_4.addWidget(self.rightPatch_3, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.rightPatch_2 = QtGui.QGraphicsView(Form)
        self.rightPatch_2.setEnabled(True)
        self.rightPatch_2.setGeometry(QtCore.QRect(910, 640, 81, 81))
        self.rightPatch_2.setAutoFillBackground(True)
        self.rightPatch_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightPatch_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.rightPatch_2.setObjectName(_fromUtf8("rightPatch_2"))
        self.label_9 = QtGui.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(790, 750, 121, 41))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(70, 580, 1011, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(560, 380, 20, 431))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_10 = QtGui.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(600, 380, 161, 16))
        self.label_10.setMouseTracking(False)
        self.label_10.setStyleSheet(_fromUtf8("\n"
"font: 87 9pt \"Arial Black\";"))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(600, 600, 171, 16))
        self.label_11.setStyleSheet(_fromUtf8("font: 87 9pt \"Arial Black\";"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(70, 380, 211, 16))
        self.label_12.setStyleSheet(_fromUtf8("font: 87 9pt \"Arial Black\";"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(70, 600, 221, 16))
        self.label_13.setStyleSheet(_fromUtf8("font: 87 9pt \"Arial Black\";"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayoutWidget_5 = QtGui.QWidget(Form)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(780, 380, 241, 21))
        self.gridLayoutWidget_5.setObjectName(_fromUtf8("gridLayoutWidget_5"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.ED_match = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.ED_match.setObjectName(_fromUtf8("ED_match"))
        self.gridLayout_5.addWidget(self.ED_match, 0, 1, 1, 1)
        self.CNN_match = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.CNN_match.setAcceptDrops(False)
        self.CNN_match.setChecked(True)
        self.CNN_match.setObjectName(_fromUtf8("CNN_match"))
        self.gridLayout_5.addWidget(self.CNN_match, 0, 0, 1, 1)
        self.NCC_match = QtGui.QRadioButton(self.gridLayoutWidget_5)
        self.NCC_match.setObjectName(_fromUtf8("NCC_match"))
        self.gridLayout_5.addWidget(self.NCC_match, 0, 2, 1, 1)
        self.gridLayoutWidget_6 = QtGui.QWidget(Form)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(780, 600, 239, 21))
        self.gridLayoutWidget_6.setObjectName(_fromUtf8("gridLayoutWidget_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ED_campare = QtGui.QRadioButton(self.gridLayoutWidget_6)
        self.ED_campare.setObjectName(_fromUtf8("ED_campare"))
        self.gridLayout_6.addWidget(self.ED_campare, 0, 1, 1, 1)
        self.CNN_compare = QtGui.QRadioButton(self.gridLayoutWidget_6)
        self.CNN_compare.setAcceptDrops(False)
        self.CNN_compare.setChecked(True)
        self.CNN_compare.setObjectName(_fromUtf8("CNN_compare"))
        self.gridLayout_6.addWidget(self.CNN_compare, 0, 0, 1, 1)
        self.NCC_compare = QtGui.QRadioButton(self.gridLayoutWidget_6)
        self.NCC_compare.setObjectName(_fromUtf8("NCC_compare"))
        self.gridLayout_6.addWidget(self.NCC_compare, 0, 2, 1, 1)
        self.gridLayoutWidget_7 = QtGui.QWidget(Form)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(310, 600, 239, 21))
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.ED_produce = QtGui.QRadioButton(self.gridLayoutWidget_7)
        self.ED_produce.setObjectName(_fromUtf8("ED_produce"))
        self.gridLayout_7.addWidget(self.ED_produce, 0, 1, 1, 1)
        self.CNN_produce = QtGui.QRadioButton(self.gridLayoutWidget_7)
        self.CNN_produce.setAcceptDrops(False)
        self.CNN_produce.setChecked(True)
        self.CNN_produce.setObjectName(_fromUtf8("CNN_produce"))
        self.gridLayout_7.addWidget(self.CNN_produce, 0, 0, 1, 1)
        self.radioButton_3 = QtGui.QRadioButton(self.gridLayoutWidget_7)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_7.addWidget(self.radioButton_3, 0, 2, 1, 1)
        self.leftSize = QtGui.QLineEdit(Form)
        self.leftSize.setEnabled(False)
        self.leftSize.setGeometry(QtCore.QRect(452, 70, 91, 31))
        self.leftSize.setStyleSheet(_fromUtf8("font: 87 9pt \"Arial Black\";"))
        self.leftSize.setObjectName(_fromUtf8("leftSize"))
        self.lineEdit_2 = QtGui.QLineEdit(Form)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(982, 70, 91, 31))
        self.lineEdit_2.setStyleSheet(_fromUtf8("font: 87 9pt \"Arial Black\";"))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_18 = QtGui.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(410, 80, 31, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(940, 80, 31, 20))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.status = QtGui.QLineEdit(Form)
        self.status.setEnabled(False)
        self.status.setGeometry(QtCore.QRect(460, 770, 101, 31))
        self.status.setStyleSheet(_fromUtf8("font: 87 9pt \"Arial Black\";"))
        self.status.setObjectName(_fromUtf8("status"))
        self.label_14 = QtGui.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(70, 650, 93, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(70, 710, 93, 21))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.length = QtGui.QLineEdit(Form)
        self.length.setGeometry(QtCore.QRect(150, 650, 111, 21))
        self.length.setObjectName(_fromUtf8("length"))
        self.Height = QtGui.QLineEdit(Form)
        self.Height.setGeometry(QtCore.QRect(150, 710, 111, 21))
        self.Height.setObjectName(_fromUtf8("Height"))
        self.pushButton_2 = QtGui.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 770, 71, 28))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.progressBar = QtGui.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(270, 770, 191, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(270, 650, 72, 21))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_16 = QtGui.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(270, 710, 72, 21))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.sr = QtGui.QLineEdit(Form)
        self.sr.setGeometry(QtCore.QRect(370, 650, 111, 21))
        self.sr.setObjectName(_fromUtf8("sr"))
        self.lineEdit_3 = QtGui.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 710, 111, 21))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.checkBox = QtGui.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(70, 770, 101, 31))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayoutWidget_3 = QtGui.QWidget(Form)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(180, 540, 181, 21))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.two = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.two.setObjectName(_fromUtf8("two"))
        self.gridLayout_3.addWidget(self.two, 0, 2, 1, 1)
        self.three = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.three.setObjectName(_fromUtf8("three"))
        self.gridLayout_3.addWidget(self.three, 0, 3, 1, 1)
        self.four = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.four.setObjectName(_fromUtf8("four"))
        self.gridLayout_3.addWidget(self.four, 0, 4, 1, 1)
        self.one = QtGui.QRadioButton(self.gridLayoutWidget_3)
        self.one.setAcceptDrops(False)
        self.one.setChecked(True)
        self.one.setObjectName(_fromUtf8("one"))
        self.gridLayout_3.addWidget(self.one, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(70, 540, 101, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.checkBox_2 = QtGui.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(370, 540, 101, 19))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.loadLeft.setText(_translate("Form", "Left View", None))
        self.loadRight.setText(_translate("Form", "Right View", None))
        self.model_2.setText(_translate("Form", "model", None))
        self.weights.setText(_translate("Form", "weights", None))
        self.leftPatch.setText(_translate("Form", "Left Patch ", None))
        self.label.setText(_translate("Form", "Row", None))
        self.label_6.setText(_translate("Form", "Colomn   ", None))
        self.predictRightPatch.setText(_translate("Form", "Match", None))
        self.label_2.setText(_translate("Form", "Colomn", None))
        self.label_8.setText(_translate("Form", "Disparity", None))
        self.label_7.setText(_translate("Form", "Row", None))
        self.label_5.setText(_translate("Form", "Dissimilarity", None))
        self.label_4.setText(_translate("Form", "Colomn", None))
        self.pushButton.setText(_translate("Form", "Right Patch ", None))
        self.label_3.setText(_translate("Form", "Row      ", None))
        self.label_9.setText(_translate("Form", " Dissimilarity", None))
        self.label_10.setText(_translate("Form", "Matching Patches", None))
        self.label_11.setText(_translate("Form", "Comparing Patches", None))
        self.label_12.setText(_translate("Form", "Extracting Left Patches", None))
        self.label_13.setText(_translate("Form", "Producing Deisparity Map", None))
        self.ED_match.setText(_translate("Form", "SSD", None))
        self.CNN_match.setText(_translate("Form", "CNN", None))
        self.NCC_match.setText(_translate("Form", "NCC", None))
        self.ED_campare.setText(_translate("Form", "SSD", None))
        self.CNN_compare.setText(_translate("Form", "CNN", None))
        self.NCC_compare.setText(_translate("Form", "NCC", None))
        self.ED_produce.setText(_translate("Form", "SSD", None))
        self.CNN_produce.setText(_translate("Form", "CNN", None))
        self.radioButton_3.setText(_translate("Form", "NCC", None))
        self.label_18.setText(_translate("Form", "SIZE", None))
        self.label_19.setText(_translate("Form", "SIZE", None))
        self.label_14.setText(_translate("Form", "Length", None))
        self.label_15.setText(_translate("Form", "Height", None))
        self.pushButton_2.setText(_translate("Form", "Produce", None))
        self.label_17.setText(_translate("Form", "Start Row", None))
        self.label_16.setText(_translate("Form", "Start Col", None))
        self.checkBox.setText(_translate("Form", "Full size", None))
        self.two.setText(_translate("Form", "3", None))
        self.three.setText(_translate("Form", "4", None))
        self.four.setText(_translate("Form", "8", None))
        self.one.setText(_translate("Form", "1", None))
        self.label_20.setText(_translate("Form", "Scale factor", None))
        self.checkBox_2.setText(_translate("Form", "Mean File", None))

